version: '3.8'

services:
    postgres:
        image: postgres:latest
        container_name: MTG_card_db
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "5432:5432"
        volumes:
            - ./pgdata:/var/lib/postgresql/data 
        networks:
            - my_netword
networks:
    my_netword:
        driver: bridge 